apiVersion: v1
kind: Service
metadata:
  name: cloudlit-django-api-service
  labels:
    app: cloudlit-django-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: cloudlit-django-api-port
    protocol: TCP
  selector:
    app: cloudlit-django-api
  type: LoadBalancer
